# For Cloud integration to work the job calling this action needs to set env: NX_CLOUD_ACCESS_TOKEN: ${ secrets.NX_CLOUD_KEY }}
name: PrValidation
description: Lints, tests and builds affected libs for PR Validation
runs:
  using: composite
  steps:
    - name: workspace lint
      shell: bash
      run: npx nx workspace-lint

    - name: lint
      shell: bash
      run: npx nx affected --target=lint

    - name: test
      shell: bash
      run: npx nx affected --target=test --ci --code-coverage

    - name: build
      shell: bash
      run: npx nx affected --target=build
