name: PR Workflow

on:
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_KEY }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: workspace lint
        shell: bash
        run: npx nx workspace-lint

      - name: lint
        shell: bash
        run: npx nx affected --target=lint

      - name: test
        shell: bash
        run: npx nx affected --target=test --ci --code-coverage

      # Have to set parallel to 1 for component-test because cypress apparently cannot run in parallel on the same machine (also doesn't work locally). Needs more investigations
      - name: component-test
        shell: bash
        run: npx nx affected --target=component-test --parallel=1  --ci --code-coverage

      # TO BE REMOVED!!
      - name: Set Version to 4.2.0
        shell: bash
        run: npm run set-versions -- 4.2.0

      - name: build
        shell: bash
        run: npx nx affected --target=build

      # TO BE REMOVED!!
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: dist
