name: PR Workflow

on:
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${ secrets.NX_CLOUD_KEY }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/pr-validation
