name: PR Workflow

on:
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${ secrets.NX_CLOUD_KEY }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: workspace lint
        shell: bash
        run: npx nx workspace-lint

      - name: lint
        shell: bash
        run: npx nx affected --target=lint

      - name: test
        shell: bash
        run: npx nx affected --target=test --ci --code-coverage

      - name: build
        shell: bash
        run: npx nx affected --target=build
