name: Publish

on:
  push:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Check npm credentials
        shell: bash
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: git config
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email "-"

      - name: Version
        shell: bash
        run: npx nx affected --base=last-release --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: git tag --force last-release

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.14.0
        with:
          token: ${{ secrets.MANAGE_REPO_TOKEN }}
          ref: ${{ github.ref }}
          tags: true
          unprotect_reviews: true
          force: true

