name: Publish

on:
  release:
    types: [published]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Parse Version
        id: parse-version
        shell: bash
        run: |
          id=$(echo ${{ github.ref_name }} | cut -dv -f2)
          echo "PARSED_VERSION=$id" >> $GITHUB_OUTPUT

      - name: Publish to npm
        shell: bash
        run: npx nx run-many --target=deploy --package-version=${{ steps.parse-version.outputs.PARSED_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
